# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'centos6'
  config.vm.box_url = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.7_chef-provisionerless.box'

  config.vm.hostname = 'mediawiki-test'

  config.vm.network 'forwarded_port', guest: 80, host: 8888

  config.vm.synced_folder 'roots/salt', '/srv/salt'
  config.vm.synced_folder 'roots/pillar', '/srv/pillar'
  config.vm.synced_folder '../mediawiki', '/srv/salt/mediawiki'

  config.vm.provision :salt do |salt|
    salt.minion_config = 'minion'
    salt.run_highstate = true
    salt.verbose = true
    salt.bootstrap_options = '-F -c /tmp/ -P'
  end
end
